apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: serverless
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: serverless
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  source:
    git:
      url: https://github.com/tanzu-demo/tap-test
      ref:
        branch: main
    subPath: serverless
