apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: frontend
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    app.kubernetes.io/part-of: frontend
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/tanzu-demo/tap-test
      ref:
        branch: main
    subPath: frontend
