apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: serverless
  description: Hello Fun
  tags:
    - app-accelerator
    - java
    - spring
    - cloud
    - serverless
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=serverless'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
